# Generated by Django 4.0 on 2021-12-15 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_answer_question_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voted_on',
            field=models.ManyToManyField(blank=True, related_name='voted_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='voted_on',
            field=models.ManyToManyField(blank=True, related_name='voted_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
