# Generated by Django 4.0 on 2021-12-16 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_question_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accepted', to='api.answer'),
        ),
    ]
