# Generated by Django 4.0 on 2021-12-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_question_downvotes_question_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='voted_on',
        ),
    ]
