# Generated by Django 4.0 on 2021-12-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tag_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
