# Generated by Django 4.0 on 2021-12-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_tag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions_tag', to='api.Tag'),
        ),
    ]
