# Generated by Django 4.0 on 2021-12-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_question_voted_on'),
        ('api', '0008_alter_question_tags'),
    ]

    operations = [
    ]
