# Generated by Django 4.0 on 2021-12-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_answer_voted_on_answer_downvotes_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('votes', 'created_at'), name='answers_votes_date'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('votes', 'created_at'), name='questions_votes_date'),
        ),
    ]
