# Generated by Django 4.0 on 2021-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_answer_voted_on_answer_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
