# Generated by Django 4.0 on 2021-12-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_image_url'),
        ('api', '0012_alter_answer_options_alter_question_options_and_more'),
    ]

    operations = [
    ]
