# Generated by Django 4.0 on 2021-12-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_question_options_remove_question_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
